api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/web-servers"
  id = "initializ-buildpacks/web-servers"
  name = "Initializ Buildpack for Web Servers"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/web-servers/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "3.6.10"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.9"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.5.5"

  [[order.group]]
    id = "initializ-buildpacks/yarn"
    version = "1.2.5"

  [[order.group]]
    id = "initializ-buildpacks/yarn-install"
    version = "1.2.5"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    version = "1.0.16"

  [[order.group]]
    id = "initializ-buildpacks/nginx"
    version = "0.15.14"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.11"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.8"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "initializ-buildpacks/source-removal"
    version = "0.2.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "3.6.10"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.9"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.5.5"

  [[order.group]]
    id = "initializ-buildpacks/npm-install"
    version = "1.3.5"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    version = "1.0.16"

  [[order.group]]
    id = "initializ-buildpacks/nginx"
    version = "0.15.14"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.11"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.8"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "initializ-buildpacks/source-removal"
    version = "0.2.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "3.6.10"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.9"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.5.5"

  [[order.group]]
    id = "initializ-buildpacks/yarn"
    version = "1.2.5"

  [[order.group]]
    id = "initializ-buildpacks/yarn-install"
    version = "1.2.5"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    version = "1.0.16"

  [[order.group]]
    id = "initializ-buildpacks/httpd"
    version = "0.7.19"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.11"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.8"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "initializ-buildpacks/source-removal"
    version = "0.2.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "3.6.10"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.9"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.5.5"

  [[order.group]]
    id = "initializ-buildpacks/npm-install"
    version = "1.3.5"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    version = "1.0.16"

  [[order.group]]
    id = "initializ-buildpacks/httpd"
    version = "0.7.19"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.11"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.8"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "initializ-buildpacks/source-removal"
    version = "0.2.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "3.6.10"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.9"

  [[order.group]]
    id = "initializ-buildpacks/nginx"
    version = "0.15.14"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.11"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.8"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "initializ-buildpacks/source-removal"
    version = "0.2.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "3.6.10"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.9"

  [[order.group]]
    id = "initializ-buildpacks/httpd"
    version = "0.7.19"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.11"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.8"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "initializ-buildpacks/source-removal"
    version = "0.2.2"
